ALL = main

all : $(ALL)
test : $(ALL)

main : chaltteok.cpp
	g++-7 -Wall -lm -static -DEVAL -g -o chaltteok -O2 chaltteok.cpp -std=c++11

backup: chaltteok2.cpp
	g++-7 -Wall -lm -static -DEVAL -g -o chaltteok -O2 chaltteok2.cpp -std=c++11
